#!/bin/bash
#PBS -N ShengBTE
#PBS -l nodes=node007:ppn=12
#PBS -j oe
#PBS -q zf
EXE='/public/bin/ShengBTE102'
OUT=LOG.bte
                                                                                    
NPROCS=$(wc -l < "$PBS_NODEFILE")
cd "$PBS_O_WORKDIR"
mpirun -machinefile "$PBS_NODEFILE" -np $NPROCS $EXE >|$OUT 2>&1
                                                                                    
/public/bin/info_job.sh
